config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
    resources :breeds
    resources :listings
    namespace :buyer do
      resources :messages
    end
    
    root to: "users#index"
  end
  
  devise_for :users
  
  resources :listings
  
  namespace :seller do
    resources :registrations
  end

  namespace :buyer do
    resources :messages
  end
  root to: "home#landing"
 get '/home', to: 'home#index', as: 'home' 
  get '/show/:id', to: 'home#show', as:'list'
  get "/membership/new", to: "membership#new", as: "new_membership"
  get "/membership", to: "membership#index", as: "membership"
  get "/membership/complete", to: "membership#complete", as: "complete_membership"
  post "/membership/webhook", to: "membership#webhook"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :breed
  belongs_to :user
  has_one_attached :picture
  has_many :buyer_messages, class_name: "Buyer::Message"

  # defines the sellers name
  def breeder_name
    user.name
  end

  # defines the sellers email
  def breeder_email
    user.email
  end

  # search query for the search bar
  def self.search(search_params) 
    return Listing.all if search_params.blank?
    Listing.joins(:breed).where("LOWER(breeds.name) LIKE LOWER(?)", "%#{search_params}%")
  end

end

app/controllers/admin/listings_controller.rb
module Admin
  class ListingsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # devise helper to authenticate first
  before_action :authenticate_user! 

  # list the listings
  def index
    @pagy, @listings = pagy(Listing.where(user: current_user))
    authorize(@listings) # pundit authorization
    @user = current_user
  end

  # define new listing
  def new
    @listing = Listing.new
    authorize(@listing) # pundit authorization
  end

  # creates new listing
  def create
    @listing = Listing.new(listing_params.merge(user: current_user))
    authorize(@listing) # pundit authorization
# checked if save
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
      else
        format.html do
          flash[:alert] = "Listing was not created due to the following: #{@listing.errors.full_messages.join(', ')}"
          render :new
        end
      end
    end
  end

  # edit listing
  def edit
    @listing = Listing.find_by(id: params[:id])
    authorize(@listing) # pundit authorization
  end

  # show listing
  def show
    @listing = Listing.find_by(id: params[:id])
    authorize(@listing) # pundit authorization
  end

  # delete listing
  def destroy
    @listing = Listing.find_by(id: params[:id])
    authorize(@listing) # pundit authorization

    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_path, notice: 'Listing was successfully destroyed.' }
    end
  end

  # updates listing
  def update
    @listing = Listing.find_by(id: params[:id])
    authorize(@listing) # pundit authorization

    respond_to do |format|
      if @listing.update(listing_params)
        #format.html { redirect_to @listing, notice: 'User was successfully updated.' }
        format.html { render :show, notice: 'Listing was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  protected
# sanitized params
  def listing_params
    params.require(:listing).permit(:description, :breed_id, :breeder_prefix, :picture)
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<br />
<%= form_with(model: listing, local: true) do |form| %>
<div class="field">
  <%- opts = options_from_collection_for_select(Breed.order(:name), :id, :name, listing.breed_id) %>
  <%= form.select_with_label(:breed_id, opts, required: true) %>
</div>
<div class="field">
  <%= form.text_field_with_label :breeder_prefix %>
</div>
<div class="field">
  <h3><%= form.label :description, "Description" %></h3>
  <%= form.text_area :description, :id => "message_area", class: "textarea"  %>
</div>
<br />
<div class="field">
  <%if @listing.picture.attached? %>
  <%= image_tag @listing.picture %>
  <% end %>
  <%= form.label :picture %>
  <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg', class:'file-label file-cta file has-name' %>
  <br /><span class='file-icon'><i class="fas fa-upload"></i></span>
</div>
<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/listings/edit.html.erb
<section class="listing-form-margin">
<div class="section">
  <br/>
  <div class="container">
  <br/>
    <div class="card">
      <div class="card-content">
        <div class="content is-small is-narrow">
          <h1>Editing Listing</h1>
            <%= render 'form', listing: @listing %>
        </div>
      </div>
    </div>
  </div>
</div>        
<div class="container">          
  <%= link_to 'Show', @listing, class:'button is-info is-small' %> |
  <%= link_to 'Back', :back, class:'button is-info is-small' %>
</div>
</section>

app/views/listings/index.html.erb
<br />
<div class='container'>
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="<%=root_path%>">Home</a></li>
      <li class="is-active"><a href="<%=listings_path%>" aria-current="page">Listings</a></li>
    </ul>
  </nav>
  <h1 class="title">Hello <%= @user.name%></h1>
  <h2 class="subtitle">Here are all your Listings</h2>
</div>
<br />
<div class=container>
  <div class=container-home>
    <% @listings.order(updated_at: :desc).each do |listing|%>
    <div class="card">
      <div class="card-content" style='font-size: small; '>
        <%= time_ago_in_words(listing.updated_at) %><span> ago</span>
      </div>
      <div class="card-image">
        <figure class="image is-4by3">
          <% if listing.picture.attached? %>
          <%= link_to listing_path(listing.id) do %>
          <%= image_tag listing.picture%>
          <%end%>
          <% else %>
          <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
          <% end %>
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <% if listing.user.avatar.attached?%>
              <%= image_tag listing.user.avatar %>
              <% else %>
              <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
              <%end%>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= link_to listing.breed.name, listing_path(id: listing.id)%></p>
            <p class="title is-4"><%= listing.breeder_prefix%></p>
            <p class="subtitle is-6"><%= listing.user.name%></p>
          </div>
        </div>
        <div class="content">
          <%= listing.description.to_s.truncate_words(40, omission: '... (continued)')%>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>
<br />
<div class='container'>
  <button class="button is-success is-small">
    <span class="icon is-small">
      <i class="fas fa-bone"></i>
    </span>
    <span><%= link_to "Post new Listing", new_listing_path %></span>
  </button>
  <%== pagy_bulma_combo_nav_js(@pagy) %>
</div>

app/views/listings/new.html.erb
<div class="section">
  <br/>
  <div class="listing-form-margin">
  <br/>
    <div class="card">
      <div class="card-content">
        <div class="content is-small is-narrow">
          <center><h1>Add New Listing</h1></center>
          <%= render 'form', listing: @listing %>
        </div>
      </div>    
    </div>  
  </div>
</div>
<div class="container">  
  <%= link_to 'Back', listings_path %>
</div>  

app/views/listings/show.html.erb
<section class="listing-form-margin">
<div class="section">
  <br />
  <div class="container">
    <%= image_tag @listing.picture if @listing.picture.attached? %>
    <br />
    <div class="card">
      <div class="card-content">
        <div class="content">
          <% listing = @listing%>
          <%= listing.breed.name %>
          <br />
          <%= listing.breeder_prefix %>
          <br />
          <%= listing.description %>
          <br />
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <span><%= link_to "Edit", edit_listing_path(id: listing.id) %> |</span>
  <span><%= link_to "Delete", listing_path(listing),data: { confirm: 'Are you sure?' }, method: :delete %> |</span>
  <span><%= link_to "Back ", root_path %></span>
</div>
</section>