config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
    resources :breeds
    resources :listings
    namespace :buyer do
      resources :messages
    end
    
    root to: "users#index"
  end
  
  devise_for :users
  
  resources :listings
  
  namespace :seller do
    resources :registrations
  end

  namespace :buyer do
    resources :messages
  end
  root to: "home#landing"
 get '/home', to: 'home#index', as: 'home' 
  get '/show/:id', to: 'home#show', as:'list'
  get "/membership/new", to: "membership#new", as: "new_membership"
  get "/membership", to: "membership#index", as: "membership"
  get "/membership/complete", to: "membership#complete", as: "complete_membership"
  post "/membership/webhook", to: "membership#webhook"
end

app/views/shared/_card.html.erb
<br />
<div class="container" style='width: 55%; '>
  <div class="card">
    <div class="card-content">
      <p class="title">
        “This is a very cool website if your looking for pets, Highly Recommended.”
      </p>
      <br />
      <p class="subtitle">
        @Navigator- CoderAcademy<span ><%=image_tag 'nav.png', width:'50px', :class => "style_image"%></span>
      </p>
    </div>
  </div>
</div>

app/views/shared/_dog_api.html.erb
<br/>
<div class='box' id="banner-message" style='padding: 2rem;'>
  <h2 class='title is-1'>Dog Facts:</h2>
<section class="hero is-medium is-dark">
  <p>Select a Breed</p>

  <select class="select is-medium  breed_select">
    <option></option>
  </select>

</div>
<div id="breed_data">
  <img id="breed_image" src="" />
  <table class='table' id="breed_data_table">

  </table>
</div>
</section>
<script> 
// Made to demonstrate how to use JQuery and TheDogAPI to load breed list, and show a breed image and data on selection. Any questions hit me up at - https://forum.thatapiguy.com - Aden

// Setup the Controls
var $breed_select = $('select.breed_select');
$breed_select.change(function() {
  var id = $(this).children(":selected").attr("id");
  getDogByBreed(id)
});
// Load all the Breeds
function getBreeds() {
  ajax_get('https://api.thedogapi.com/v1/breeds', function(data) {
    populateBreedsSelect(data)
  });
}
// Put the breeds in the Select control
function populateBreedsSelect(breeds) {
  $breed_select.empty().append(function() {
    var output = '';
    $.each(breeds, function(key, value) {
      output += '<option id="' + value.id + '">' + value.name + '</option>';
    });
    return output;
  });
}
// triggered when the breed select control changes
function getDogByBreed(breed_id) {
  // search for images that contain the breed (breed_id=) and attach the breed object (include_breed=1)
  ajax_get('https://api.thedogapi.com/v1/images/search?include_breed=1&breed_id=' + breed_id, function(data) {

    if (data.length == 0) {
      // if there are no images returned
      clearBreed();
      $("#breed_data_table").append("<tr><td>Sorry, no Image for that breed yet</td></tr>");
    } else {
      //else display the breed image and data
      displayBreed(data[0])
    }
  });
}
// clear the image and table
function clearBreed() {
  $('#breed_image').attr('src', "");
  $("#breed_data_table tr").remove();
}
// display the breed image and data
function displayBreed(image) {
  $('#breed_image').attr('src', image.url);
  $("#breed_data_table tr").remove();

  var breed_data = image.breeds[0]
  $.each(breed_data, function(key, value) {
    // as 'weight' and 'height' are objects that contain 'metric' and 'imperial' properties, just use the metric string
    if (key == 'weight' || key == 'height') value = value.metric
    // add a row to the table
    $("#breed_data_table").append("<tr><td>" + key + "</td><td>" + value + "</td></tr>");
  });
}

// make an Ajax request
function ajax_get(url, callback) {
  var xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
      console.log('responseText:' + xmlhttp.responseText);
      try {
        var data = JSON.parse(xmlhttp.responseText);
      } catch (err) {
        console.log(err.message + " in " + xmlhttp.responseText);
        return;
      }
      callback(data);
    }
  };

  xmlhttp.open("GET", url, true);
  xmlhttp.send();
}
// call the getBreeds function which will load all the Dog breeds into the select control
getBreeds();

</script>

app/views/shared/_footer.html.erb
<footer class="footer" style='padding: 2rem;'>
  <div class="content has-text-centered">
    <p>
      <span><i class="fas fa-paw"></i></span><strong>Manspalhouse&copy</strong> 2020 by W Esmundo. Coder Academy.
    </p>
  <a href="https://bulma.io">
<img src="https://bulma.io/images/made-with-bulma--dark.png" alt="Made with Bulma" width="128" height="24">
</a>
  </div>
</footer>

app/views/shared/_hero.html.erb
<section class="hero is-large is-white ">
  <div class="hero-body">
    <div class="container">
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<!-- START NAV -->
<nav class="navbar is-white is spaced">
  <div class="container">
    <div class="navbar-brand">
      <button class="button is-white is-medium">
        <span class="icon"><i class="fa fa-paw"></i></span>
        <span><%= link_to "MansPalHouse", root_path%></span>
      </button>
      <span class="navbar-burger burger" data-target="navbarMenu">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navbarMenu" class="navbar-menu">
      <div class="navbar-end">
        <span class="navbar-item">
          <%= link_to 'Home', root_path%><span class="icon">
            <i class="fas fa-home"></i>
          </span>
        </span>
        <% if user_signed_in? && current_user.guest? %>
        <span class="navbar-item button is-info is-light is-medium is-outlined">
          <%= link_to "Apply as Seller", new_seller_registration_path %>
          <% end %>
        </span>
        <%if user_signed_in?%>
        <span class="navbar-item">Welcome, <%= current_user.email%></span>
        </span>
        <div class="navbar-item has-dropdown is-hoverable">
          <span class="navbar-link">
            Account<span><i class="fas fa-user-circle"></i></span>
          </span>
          <div class="navbar-dropdown">
            <div class="navbar-item">
              <span class="navbar-item"><%= link_to 'Profile',edit_user_registration_path %></span>
            </div>
            <% if current_user.seller? && current_user.completed? || current_user.admin?%>
            <div class="navbar-item">
              <span class="navbar-item"><%= link_to 'Listings',listings_path %></span>
            </div>
            <%end%>
            <% if current_user.admin?%>
            <div class="navbar-item">
              <span class="navbar-item"><%= link_to 'Admin Dashboard',admin_users_path %></span>
            </div>
            <%end%>
            <% if current_user.seller? && current_user.approved?%>
            <div class="navbar-item">
              <span class="navbar-item"><%= link_to 'Make Payments',new_membership_path %></span>
            </div>
            <%end%>
            <hr class="navbar-divider">
            <div class="navbar-item">
              <span class="navbar-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </span>
            </div>
          </div>
        </div>
      </div>
      <%else%>
      <span class="navbar-item">
        <%= link_to "Sign In", new_user_session_path %><span><i class="fas fa-sign-in-alt"></i></span>
      </span>
      <span class="navbar-item">
        <%=link_to "Register", new_user_registration_path%><span><i class="fas fa-user-plus"></i></span>
      </span>
      <%end%>
    </div>
  </div>
</nav>
<!-- END NAV -->

app/views/shared/_search.html.erb
<%# Search Bar %>
<br />
<div class="container" style=" width: 50%;">
  <%= form_tag(home_path, method: :get, id: 'search-bar') do%>
  <div class="section">
    <div class="box">
      <div class="field has-addons">
        <div class="control is-expanded">
          <%= text_field_tag(:search, params[:search],placeholder: "»»» search dogs here «««", class: "input has-text-centered")%>
        </div>
        <div class="control">
          <%= submit_tag ('Search...'), class:"button is-info"%>
        </div>
      </div>
      <%end%>
    </div>
  </div>
</div>
<%# end Seacrch Bar %>