config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
    resources :breeds
    resources :listings
    namespace :buyer do
      resources :messages
    end
    
    root to: "users#index"
  end
  
  devise_for :users
  
  resources :listings
  
  namespace :seller do
    resources :registrations
  end

  namespace :buyer do
    resources :messages
  end
  root to: "home#landing"
 get '/home', to: 'home#index', as: 'home' 
  get '/show/:id', to: 'home#show', as:'list'
  get "/membership/new", to: "membership#new", as: "new_membership"
  get "/membership", to: "membership#index", as: "membership"
  get "/membership/complete", to: "membership#complete", as: "complete_membership"
  post "/membership/webhook", to: "membership#webhook"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:contact_seller]

  def new
  end

  def landing
  end
  # list all the listings
  def index
    @users = User.all
    @user_count = User.count
    @pagy, @listings = pagy(Listing.search(params[:search]))
  end
  # shows the listing
  def show
    @listing = Listing.find_by(id: params[:id])
  end

end

app/views/home/index.html.erb
<div class='container'>
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="<%=root_path%>">Home</a></li>
      <li class="is-active"><a href="#" aria-current="page">Listings</a></li>
    </ul>
  </nav>
</div>
<br/>
<%= render '/shared/search'%>
<section class="section">
  <div id="main" class='container' style='text-align:center;'>
    <h1 class="title">Available</h1>
    <h2 class="subtitle">Listings</h2>
  </div>
  <br />
  <div class='container-home search-results'>
    <% @listings.order(updated_at: :desc).each do |listing|%>
    <div class="card">
      <div class="card-content" style='font-size: small; '>
        <%= time_ago_in_words(listing.updated_at) %><span> ago</span>
      </div>
      <div class="card-image">
        <figure class="image is-4by3">
          <% if listing.picture.attached? %>
          <%= link_to list_path(listing.id) do %>
          <%= image_tag listing.picture%>
          <%end%>
          <% else %>
          <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
          <% end %>
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <% if listing.user.avatar.attached?%>
              <%= image_tag listing.user.avatar %>
              <% else %>
              <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
              <%end%>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4">Breed: <%= link_to listing.breed.name, list_path(id: listing.id)%></p>
            <p class="title is-4">Kennel: <%= listing.breeder_prefix%></p>
            <p class="subtitle is-6">Breeder: <%= listing.user.name%></p>
            <p class="subtitle is-6 buttons"><%= link_to 'Price: Contact Seller', new_buyer_message_path(listing_id: listing.id),
            class:'button is-small is-rounded is-info'%></p>
          </div>
        </div>
        <div class="content"><p class="subtitle is-6">Description: 
          <%= listing.description.to_s.truncate_words(40, omission: '... (continued)') %></p>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</section>
<section class='section'>
  <%== pagy_bulma_combo_nav_js(@pagy) %>
</section>


  

app/views/home/landing.html.erb
<%= render '/shared/search'%>
<%= render '/shared/hero'%>
<br />
<div  class="container" style='text-align: center; padding: 2rem;'>
  <h2 class="subtitle is-5 is-spaced ">Planning on getting a <strong>puppy</strong>?</h2>
  <h2 class="subtitle is-5 is-spaced ">If you have already settled on a breed,
    the next big decision is where you should get your <strong>puppy</strong> from. </h2>
</div>

<%= render '/shared/card'%>
<br />
<%= render '/shared/dog_api'%>
<footer class='footer'>
<div class='container' style='display:flex; justify-content:space-between; '>
<span><%=image_tag('logo4.png')%></span><span><%=image_tag('logo1.png')%></span><span><%=image_tag('logo2.png')%></span><span><%=image_tag('logo3.png')%></span></div>
</footer>

app/views/home/landing_page.html.erb
<%# Search Bar %>
<br />
<div class="container" style=" width: 50%;">
  <%= form_tag("#{home_path+'#main'}", method: :get) do%>
  <div class="section">
    <div class="box">
      <div class="field has-addons">
        <div class="control is-expanded">
          <%= text_field_tag(:search, params[:search],placeholder: "» search dogs here «", class: "input has-text-centered")%>
        </div>
        <div class="control">
          <%= submit_tag ('Search...'), class:"button is-info"%>
        </div>
      </div>
      <%end%>
    </div>
  </div>
</div>
<%# end Seacrch Bar %>
<%= render '/shared/hero'%>
<br />
<div  class="container" style='text-align: center; padding: 2rem;'>
  <h2 class="subtitle is-5 is-spaced ">Planning on getting a <strong>puppy</strong>?</h2>
  <h2 class="subtitle is-5 is-spaced ">If you have already settled on a breed,
    the next big decision is where you should get your <strong>puppy</strong> from. </h2>
</div>

<%= render '/shared/card'%>
<br />
<%= render '/shared/dog_api'%>

app/views/home/show.html.erb
<section class="listing-form-margin">
<div class="section">
  <br />
  <div class="container">
    <%= image_tag @listing.picture if @listing.picture.attached? %>
    <br />
    <div class="card">
      <div class="card-content">
        <div class="content">
          <% listing = @listing%>
          <p><strong>Breed: </strong> <%= listing.breed.name %></p>
          <br />
          <p><strong>Kennel: </strong> <%= listing.breeder_prefix %></p>
          <br />
          <p><span><strong>Share:</strong> </span><span><%= social_share_button_tag(@listing.breed.name) %></span></p>
          <p><strong>Description: </strong> <%= listing.description %></p>
          <br />
          <p class='buttons'><%= link_to 'Price: Contact Seller', new_buyer_message_path(listing_id: listing.id),
            class:'button is-small is-rounded is-info'%></p>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back%>
</section>