config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :users
    resources :breeds
    resources :listings
    namespace :buyer do
      resources :messages
    end
    
    root to: "users#index"
  end
  
  devise_for :users
  
  resources :listings
  
  namespace :seller do
    resources :registrations
  end

  namespace :buyer do
    resources :messages
  end
  root to: "home#landing"
 get '/home', to: 'home#index', as: 'home' 
  get '/show/:id', to: 'home#show', as:'list'
  get "/membership/new", to: "membership#new", as: "new_membership"
  get "/membership", to: "membership#index", as: "membership"
  get "/membership/complete", to: "membership#complete", as: "complete_membership"
  post "/membership/webhook", to: "membership#webhook"
end

app/controllers/membership_controller.rb
class MembershipController < ApplicationController
  # devise helper for authentication
  skip_before_action :verify_authenticity_token, only: [:webhook]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:webhook]
  
  # creates user and session for stripe
  def new
    @user = current_user
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name:"Payee: #{@user.name}",
        description:'MansPalHouse Membership Payment',
        amount: 5000,
        currency:'aud',
        quantity: 1,
      }],
      payment_intent_data: {
        metadata: {
          user_id: @user.id
        }
      },
      success_url: "#{root_url}membership/complete",
      cancel_url: "#{root_url}",
   )
 end

  # saves data for user to check if payment went thru and change user application status to completed
 def webhook
    payment_id= params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    user_id = payment.metadata.user_id
    user = User.find(user_id)
    user.update_attributes(stripe_payment_id: payment_id)
    user.application_status = 'completed'
    user.save
  end

  def index
  end

  def complete
  end
end

app/helpers/membership_helper.rb
module MembershipHelper
end

app/views/membership/complete.html.erb
<div class='container'>
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="<%=root_path%>">Home</a></li>
      <li class="is-active"><a href="#" aria-current="page">Payment</a></li>
    </ul>
  </nav>
</div>
<div class='container' style='width:50%; padding: 6rem 6rem 10rem;'>
  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        Payment Confirm.
      </p>
      <a href="#" class="card-header-icon" aria-label="more options">
        <span class="icon">
          <i class="fas fa-check"></i>
        </span>
      </a>
    </header>
    <div class="card-content">
      <div class="content">
        Thanks. Payment has now been verified. If you wish to proceed and add listings, puppy ads or dog profiles,
        just hit the button below and that will take you to the listing page.
        <br>
      </div>
    </div>
    <footer class="card-footer">
      <%= link_to 'Add Listing', listings_path, class:"card-footer-item"%>
      <%= link_to 'Main Menu', root_path, class:"card-footer-item"%>
    </footer>
  </div>
</div>

app/views/membership/index.html.erb
<div class='container'>
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="<%=root_path%>">Home</a></li>
      <li class="is-active"><a href="#" aria-current="page">Membership</a></li>
    </ul>
  </nav>
</div>
<section class='section'>
  <div class='container' style='text-align:center;'>
    <h1><strong>Congratulations!</strong> Your one step away on become a member</h1><br />
    <p>for <strong>$50.00</strong> you will have access to the following features:</p><br />
    <br />
    
    <div class='container' style='display:flex; justify-content:space-between; bottom-padding: 2rem;'>
      <article class="message is-info">
        <div class="message-header">
          <p>Breeders Listing</p>
        </div>
        <div class="message-body">
          <p>Unlimited number of Breed</p>
          <p>Listings</p>
        </div>
      </article>

      <article class="message is-info">
        <div class="message-header">
          <p>Puppy (Litter) Notices</p>
        </div>
        <div class="message-body">
          <p> Listing for Puppies</p>
        </div>
      </article>

      <article class="message is-info">
        <div class="message-header">
          <p>Older Dog Listing</p>
        </div>
        <div class="message-body">
          <p>Advertise</p>
          <p>Matured Dogs for Sale</p>
        </div>
      </article>
      <article class="message is-info">
        <div class="message-header">
          <p>Stud Services</p>
        </div>
        <div class="message-body">
          <p>Stud Dogs</p>
          <p>Listings</p>
        </div>
      </article>
    </div>
  </div>
  <p style='margin: 2.5rem 0;'><%= link_to 'Proceed to Payment', new_membership_path, class:'button is-primary'%></p>
</section>

app/views/membership/new.html.erb
<div class='container'>
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="<%=root_path%>">Home</a></li>
      <li><a href="<%=membership_path%>">Membership</a></li>
      <li class="is-active"><a href="#" aria-current="page">Checkout</a></li>
    </ul>
  </nav>
</div>
<div class='container' style='text-align: center; width:50%; padding: 3rem ;'>
  <div class='card' style='padding: 5rem 0;'>
    <h2 class='title is-2'>Checkout</h2>
    <div class="columns">
      <div class="column">
        <strong>Details</strong>
      </div>
      <div class="column">
        <strong>Price</strong>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        Subscription for MansPalhouse
      </div>
      <div class="column">
        $50.00 AUD
      </div>
    </div>
    <br />
    <div class="columns">
      <div class="column">
        Payment Method
      </div>
      <div class="column">
        <label class="radio">
            <input type="radio" name="foobar" checked>
            Credit Card
          </label>
        </div>
    </div>
</div>
<button id="pay-now" class="field has-addons control" style='margin: 2rem 0;'>Pay now <a><i
        class="fab fa-stripe"></a></i></button>

<script src="https://js.stripe.com/v3/"></script>
<script>
 document
   .querySelector("[id='pay-now']")
   .addEventListener("click", () => {
     const stripe = Stripe(
       "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
     );

     stripe.redirectToCheckout({
       sessionId: "<%= @session.id %>"
     });
   });
</script>